import type { Metadata } from "next";
import "./globals.css";
import Background from "@/components/Background";
import { I18nProvider } from "@/hooks/useI18n";

export const metadata: Metadata = {
  title: "Quiz Attack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Background />
        <I18nProvider>{children}</I18nProvider>
      </body>
    </html>
  );
}
